### PR TITLE
#159 Add missing phaser-ce builds

### LINKED ISSUE #159: Add missing phaser-ce builds
https://github.com/photonstorm/phaser-ce/issues/80
pull request coming straight after this issue report

### PR DESCRIPTION
**Pull request by vpmedia**
Fixes #159
Note: I did NOT found Phaser-CE build version 2.7.0, 2.7.1, 2.7.2 - so they are still missing.

### CODE REVIEW

**Comment by samme** [comment]
2.7.0–2.7.2 can be found in <https://github.com/photonstorm/phaser-ce/releases>.

**Comment by vpmedia** [comment]
I see release v2.6.2 on Aug 26 2016 followed by v.2.7.3 on Jan 9 - nothing in-between... Am I missing something?

**Comment by samme** [comment]
I really thought I saw it there, but you're right. 😄 

If you're up for it you can install (separately) and copy each of

    npm i phaser-ce@2.7.0
    npm i phaser-ce@2.7.1
    npm i phaser-ce@2.7.2

**Comment by vpmedia** [comment]
I've added the missing files (2.7.0 .. 2.7.2)

**Pull request merged**
